name: Diploma CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Обновили до v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2 # Обновили до v2
        with:
          # Исправили название параметра:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Tools (YC and Helm)
        run: |
          curl -sSL https://yandexcloud.net | bash -s -- -n
          
          curl https://githubusercontent.com | bash

      - name: Configure K8s Access and Deploy
        run: |
          export PATH=$PATH:$HOME/yandex-cloud/bin
          
          # Авторизация через файл ключа
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa-key.json
          yc config profile create sa-profile
          yc config set service-account-key sa-key.json
          
          yc managed-kubernetes cluster get-credentials ${{ secrets.YC_K8S_CLUSTER_ID }} --external
          
          helm upgrade --install my-release ./my-app-chart \
            --set image=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }}
