name: Diploma CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Yandex Container Registry
        uses: yc-actions/yc-cr-login@v2
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_KEY }}

      - name: Build and Push Docker Image
        run: |
          docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }} .
          docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to K8s
        run: |
          curl -sSL --retry 5 https://storage.yandexcloud.net -o ./yc
          chmod +x ./yc
          
          # 2. Скачиваем Helm
          curl -sSL --retry 5 https://helm.sh | tar xz
          mv linux-amd64/helm ./helm
          chmod +x ./helm

          # 3. Авторизация
          echo '${{ secrets.YC_SA_JSON_KEY }}' > sa-key.json
          ./yc config profile create sa-profile
          ./yc config set service-account-key sa-key.json
          
          # 4. Получение конфига кластера (используем ID из секретов)
          ./yc managed-kubernetes cluster get-credentials ${{ secrets.YC_K8S_CLUSTER_ID }} --external
          
          # 5. Деплой
          ./helm upgrade --install my-release ./my-app-chart \
            --set image=cr.yandex/${{ secrets.YC_REGISTRY_ID }}/diploma-app:${{ github.sha }}
